# Generated by Django 3.1.7 on 2021-02-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
